version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: oc_pizza
      POSTGRES_PASSWORD: "VTCpRWKiJ8tygCvi7Xj9P6f2Pc3ugoil"
    volumes:
      - oc_pizza_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "4APJIq6GLdxZ1LP5S2xhCFBftbh7qmqm"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  oc_pizza_data:
